#!/usr/bin/env bash
# Live E2E smoke matrix for the compiled dist/sshepherd binary, run against a disposable
# local Docker fixture (scripts/sshd-fixture/) — an sshd container plus sibling postgres
# and app containers under the same docker daemon. Spot-checks the read-only command
# shapes, the db introspection SQL, and a deploy dry-run against a REAL Linux host, closing
# the "doc-derived, never live-driven" gap carried forward from Phases 3-6 (see
# docs/plan/2026-07-12-sshepherd-v1/plan.md Progress log).
#
# Requires Docker. A fresh ed25519 keypair is generated per run (never committed) and a
# temporary Host block is appended to ~/.ssh/config for the duration of this script, then
# removed — see teardown() below.
set -euo pipefail

BIN="${BIN:-./dist/sshepherd}"
FIXTURE_DIR="scripts/sshd-fixture"
ALIAS="sshepherd-smoke"
SSH_PORT="${SSHEPHERD_SMOKE_SSH_PORT:-2222}"
MARKER_BEGIN="# >>> sshepherd-smoke (auto-generated by scripts/smoke.sh) >>>"
MARKER_END="# <<< sshepherd-smoke <<<"
SSH_CONFIG="$HOME/.ssh/config"

WORKDIR="$(mktemp -d)"
KEYDIR="$WORKDIR/smoke-keys"
mkdir -p "$KEYDIR"

PASS_COUNT=0
step() { printf '\n[STEP] %s\n' "$1"; }
pass() {
  PASS_COUNT=$((PASS_COUNT + 1))
  printf 'PASS: %s\n' "$1"
}
fail() {
  printf 'FAIL: %s\n' "$1" >&2
  exit 1
}

# -- ssh config block management --------------------------------------------------------------
# Strips any leftover marker block from a prior crashed run before appending a fresh one, so
# repeated runs never accumulate duplicate Host entries for the same alias.
strip_marker_block() {
  if [[ -f "$SSH_CONFIG" ]] && grep -qF "$MARKER_BEGIN" "$SSH_CONFIG"; then
    python3 -c "
import sys
path = sys.argv[1]
begin, end = sys.argv[2], sys.argv[3]
lines = open(path).read().splitlines(keepends=True)
out = []
skipping = False
for line in lines:
    if line.strip() == begin:
        skipping = True
        continue
    if line.strip() == end:
        skipping = False
        continue
    if not skipping:
        out.append(line)
open(path, 'w').writelines(out)
" "$SSH_CONFIG" "$MARKER_BEGIN" "$MARKER_END"
  fi
}

append_marker_block() {
  mkdir -p "$HOME/.ssh"
  touch "$SSH_CONFIG"
  chmod 600 "$SSH_CONFIG"
  {
    printf '%s\n' "$MARKER_BEGIN"
    printf 'Host %s\n' "$ALIAS"
    printf '  HostName 127.0.0.1\n'
    printf '  Port %s\n' "$SSH_PORT"
    printf '  User root\n'
    printf '  IdentityFile %s\n' "$KEYDIR/id_ed25519"
    printf '  IdentitiesOnly yes\n'
    printf '  StrictHostKeyChecking accept-new\n'
    printf '  UserKnownHostsFile %s\n' "$WORKDIR/known_hosts"
    printf '%s\n' "$MARKER_END"
  } >>"$SSH_CONFIG"
}

# -- cleanup ------------------------------------------------------------------------------------
on_exit() {
  local status=$?
  strip_marker_block
  (cd "$FIXTURE_DIR" && SSHEPHERD_SMOKE_KEYDIR="$KEYDIR" SSHEPHERD_SMOKE_SSH_PORT="$SSH_PORT" \
    docker compose down --volumes >/dev/null 2>&1) || true
  rm -rf "$WORKDIR"
  exit "$status"
}
trap on_exit EXIT

# -- fixture bring-up -----------------------------------------------------------------------

step "generate ephemeral ssh keypair"
ssh-keygen -q -t ed25519 -N '' -f "$KEYDIR/id_ed25519"
cp "$KEYDIR/id_ed25519.pub" "$KEYDIR/authorized_keys"
chmod 600 "$KEYDIR/id_ed25519" "$KEYDIR/authorized_keys"
pass "keypair generated at $KEYDIR"

step "bring up sshd + postgres + app fixture (docker compose)"
(cd "$FIXTURE_DIR" && SSHEPHERD_SMOKE_KEYDIR="$KEYDIR" SSHEPHERD_SMOKE_SSH_PORT="$SSH_PORT" \
  docker compose up -d --build)
pass "fixture containers started"

step "wait for sshd to accept connections"
for _ in $(seq 1 30); do
  if (exec 3<>"/dev/tcp/127.0.0.1/$SSH_PORT") 2>/dev/null; then
    exec 3>&- 3<&-
    break
  fi
  sleep 1
done
pass "sshd is accepting connections on port $SSH_PORT"

step "register ssh alias '$ALIAS' in $SSH_CONFIG (temporary, removed on exit)"
strip_marker_block
append_marker_block
pass "ssh alias registered"

step "write fixture targets.toml + deploy recipe"
cat >"$WORKDIR/targets.toml" <<EOF
[smoke]
alias = "$ALIAS"
container = "sshepherd-fixture-postgres"
user = "sshepherd_ro"
database = "fixture"
EOF
cat >"$WORKDIR/deploy.smoke.toml" <<EOF
name = "smoke"
alias = "$ALIAS"
workdir = "/root"
description = "Smoke-test recipe — exercised with --dry-run only, never actually run"

[[step]]
name = "check-app"
kind = "shell"
run = "docker ps"
mutates = false

[rollback]
strategy = "compose-file"
file = "docker-compose.yml"
EOF
export SSHEPHERD_TARGETS_PATH="$WORKDIR/targets.toml"
export SSHEPHERD_RECIPE_PATH="$WORKDIR/deploy.smoke.toml"
export SSHEPHERD_FILES_ALLOWLIST_PATH="$WORKDIR/files-allowlist.toml"
export SSHEPHERD_TUNNEL_STATE_DIR="$WORKDIR/tunnels"
pass "fixture config written"

# -- CLI drive helpers ------------------------------------------------------------------------

run_cli() {
  local label="$1"
  shift
  if ! "$BIN" "$@" >"$WORKDIR/$label.json" 2>"$WORKDIR/$label.err"; then
    cat "$WORKDIR/$label.err" >&2
    fail "command failed: $BIN $*"
  fi
}

# Asserts a Python boolean expression (referencing `d`, the parsed JSON envelope from
# $WORKDIR/<label>.json) is true. Never touches credentials — assertions only read
# structural/content fields, never host/user/port (which the envelope doesn't carry anyway).
assert_json() {
  local desc="$1" label="$2" expr="$3"
  if ! python3 -c "
import json
d = json.load(open('$WORKDIR/$label.json'))
import sys
sys.exit(0 if bool($expr) else 1)
"; then
    printf '  -- response was:\n' >&2
    head -c 2000 "$WORKDIR/$label.json" >&2
    printf '\n' >&2
    fail "$desc"
  fi
  pass "$desc"
}

# -- read-only spot checks, one representative op per group -----------------------------------

step "hosts test"
run_cli hosts_test hosts test "$ALIAS"
assert_json "hosts test: ok + reachable" hosts_test "d['ok'] is True and d['data']['reachable'] is True"

step "check overview"
run_cli check_overview check overview "$ALIAS"
assert_json "check overview: ok + dead_end_risk is boolean" check_overview \
  "d['ok'] is True and isinstance(d['data']['dead_end_risk'], bool) and d['data']['nproc'] > 0"

step "services ps"
run_cli services_ps services ps "$ALIAS"
assert_json "services ps: non-empty container list" services_ps \
  "d['ok'] is True and isinstance(d['data'], list) and len(d['data']) >= 2"

step "logs docker (app container)"
run_cli logs_docker logs docker "$ALIAS" sshepherd-fixture-app --tail 5
assert_json "logs docker: LogsResult shape present" logs_docker \
  "d['ok'] is True and 'lines' in d['data'] and 'next_since' in d['data']"

step "setup files-allowlist scaffold (real scaffold path, not a hand-written TOML)"
run_cli setup_files_allowlist setup files-allowlist scaffold "$ALIAS" --paths /root --yes
assert_json "files-allowlist scaffolded for /root" setup_files_allowlist \
  "d['ok'] is True and '/root' in d['data']['paths']"

step "files ls"
run_cli files_ls files ls "$ALIAS" /root
assert_json "files ls: array of entries" files_ls \
  "d['ok'] is True and isinstance(d['data'], list)"

step "security listeners"
run_cli security_listeners security listeners "$ALIAS"
assert_json "security listeners: sshd's own port 22 is listed" security_listeners \
  "d['ok'] is True and any(e['port'] == 22 for e in d['data']['listening'])"

step "db list"
run_cli db_list db list
assert_json "db list: fixture target declared" db_list \
  "d['ok'] is True and 'smoke' in d['data']['targets']"

step "db tables"
run_cli db_tables db tables smoke
assert_json "db tables: smoke_fixture table present" db_tables \
  "d['ok'] is True and any(t['table'] == 'smoke_fixture' for t in d['data'])"

step "db query"
run_cli db_query db query smoke "SELECT note FROM smoke_fixture"
assert_json "db query: seeded row comes back" db_query \
  "d['ok'] is True and d['data'][0]['note'] == 'hello from sshepherd smoke fixture'"

step "deploy run --dry-run"
run_cli deploy_dry_run deploy run smoke --dry-run
assert_json "deploy run --dry-run: plan has steps, nothing executed" deploy_dry_run \
  "d['ok'] is True and len(d['data']['steps']) == 1 and d['data']['steps'][0]['name'] == 'check-app'"

# -- tunnel: live local port-forward (REQUIRES DOCKER, same as every step above) --------------
# Opens a kind=local forward from the fixture alias to the sibling nginx `app` container,
# reachable as `app:80` on the fixture's own docker-compose network (the sshd container resolves
# the sibling service by name), curls through the auto-assigned local port to prove real bytes
# traverse the tunnel, then closes it and confirms the local port is released.

step "tunnel open (local forward to the fixture app container's nginx on app:80)"
run_cli tunnel_open tunnel open "$ALIAS" --kind local --remote app:80 --duration 120 --yes
assert_json "tunnel open: ok + local kind + auto-assigned localPort" tunnel_open \
  "d['ok'] is True and d['data']['kind'] == 'local' and isinstance(d['data']['localPort'], int) and d['data']['id'].startswith('t-')"

TUNNEL_ID="$(python3 -c "import json; print(json.load(open('$WORKDIR/tunnel_open.json'))['data']['id'])")"
TUNNEL_PORT="$(python3 -c "import json; print(json.load(open('$WORKDIR/tunnel_open.json'))['data']['localPort'])")"

step "wait for the ssh forward to bind local port $TUNNEL_PORT"
for _ in $(seq 1 30); do
  if (exec 3<>"/dev/tcp/127.0.0.1/$TUNNEL_PORT") 2>/dev/null; then
    exec 3>&- 3<&-
    break
  fi
  sleep 1
done
pass "local port $TUNNEL_PORT is accepting connections"

step "curl through the forwarded local port (real response from the fixture nginx)"
if curl -fsS "http://127.0.0.1:$TUNNEL_PORT/" | grep -qi 'nginx'; then
  pass "tunnel carried a real HTTP response from the fixture nginx"
else
  fail "no nginx response through the tunnel on 127.0.0.1:$TUNNEL_PORT"
fi

step "tunnel list (the open tunnel is reported active)"
run_cli tunnel_list tunnel list
assert_json "tunnel list: the opened tunnel id is present + active" tunnel_list \
  "d['ok'] is True and any(t['id'] == '$TUNNEL_ID' and t['remainingSec'] > 0 for t in d['data']['tunnels'])"

step "tunnel close"
run_cli tunnel_close tunnel close "$TUNNEL_ID" --yes
assert_json "tunnel close: closed is True" tunnel_close \
  "d['ok'] is True and d['data']['closed'] is True"

step "confirm local port $TUNNEL_PORT is released after close"
released=false
for _ in $(seq 1 30); do
  if ! (exec 3<>"/dev/tcp/127.0.0.1/$TUNNEL_PORT") 2>/dev/null; then
    released=true
    break
  fi
  sleep 1
done
if [[ "$released" == true ]]; then
  pass "local port $TUNNEL_PORT released after tunnel close"
else
  fail "local port $TUNNEL_PORT still accepting connections after tunnel close"
fi

printf '\n%d/%d smoke checks passed.\n' "$PASS_COUNT" "$PASS_COUNT"
